version: "3.9"
services:
  cms-be:
    build: 
      dockerfile: Dockerfile 
      context: ./be
    container_name: cms-be
    volumes:
      - ./be:/app
    ports:
      - "3000:3000"
    restart: always
    dns:
      - 8.8.8.8   # Google DNS
      - 1.1.1.1   # Cloudflare DNS
    env_file:
      - ./be/.env
  
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cms"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: qwe123qwe
      POSTGRES_DB: cms
    ports:
      - 5432:5432
